import type {
  Product,
  Category,
  Testimonial,
  TasteCategory,
  OccasionCategory,
  TrustStat,
} from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "Mini Khakhra Discovery Pack – Assorted 4 Flavours",
    slug: "mini-khakhra-discovery-pack",
    price: 169,
    originalPrice: 199,
    rating: 4.5,
    reviewCount: 98,
    image: "/images/products/mini-khakhra-discovery.png",
    category: "mini-khakhra",
    badge: "-15%",
    description:
      "A perfect mix of top-selling flavours for every taste. Pack of 4 assorted flavours.",
    flavours: ["Methi Masala", "Chat Chaska", "Peri Peri Punch", "Cream Onion"],
    weight: "200g",
    urgencyText: "32 People Ordered this in Last 3 Days",
  },
  {
    id: "2",
    name: "Millet Moong Crunch Duo",
    slug: "millet-moong-crunch-duo",
    price: 249,
    originalPrice: 299,
    rating: 4.3,
    reviewCount: 45,
    image: "/images/products/millet-moong-crunch.png",
    category: "healthy-chips",
    badge: "-17%",
    description:
      "Crunchy millet & moong combo chips. High in protein, low in fat.",
    weight: "300g",
  },
  {
    id: "3",
    name: "Classic Bakarwadi Mix – Pack of 3",
    slug: "classic-bakarwadi-mix",
    price: 329,
    originalPrice: 399,
    rating: 4.7,
    reviewCount: 76,
    image: "/images/products/classic-bakarwadi.png",
    category: "bakarwadi",
    badge: "-18%",
    description:
      "Traditional Pune-style Bakarwadi, crispy outside and spiced filling inside.",
    weight: "450g",
  },
  {
    id: "4",
    name: "Premium Grain Fusion Combo",
    slug: "premium-grain-fusion-combo",
    price: 449,
    originalPrice: 549,
    rating: 4.6,
    reviewCount: 34,
    image: "/images/products/grain-fusion-combo.png",
    category: "healthy-chips",
    badge: "-18%",
    description: "A fusion of Ragi, Quinoa, and Oats chips in one combo.",
    weight: "500g",
  },
  {
    id: "5",
    name: "Cheese Garlic Mini Khakhra – Family Pack",
    slug: "cheese-garlic-mini-khakhra",
    price: 219,
    originalPrice: 259,
    rating: 4.4,
    reviewCount: 11,
    image: "/images/products/cheese-garlic-khakhra.png",
    category: "mini-khakhra",
    badge: "-15%",
    description:
      "Cheesy and garlicky mini khakhras, perfect for family snacking.",
    weight: "400g",
  },
  {
    id: "6",
    name: "All Rounder Bestseller Pack – Twin Packs",
    slug: "all-rounder-bestseller-pack",
    price: 1249,
    originalPrice: 1449,
    rating: 4.8,
    reviewCount: 0,
    image: "/images/products/all-rounder-pack.png",
    category: "combo",
    badge: "-14%",
    description:
      "This all-rounder combo brings together Methi Masala, Chat Chaska, Peri Peri Punch, Cream Onion, and Cheese Garlic.",
    flavours: [
      "Methi Masala",
      "Chat Chaska",
      "Peri Peri Punch",
      "Cream Onion",
      "Cheese Garlic",
    ],
    weight: "400g each",
    urgencyText: "19 People Ordered this in Last 3 Days",
  },
  {
    id: "7",
    name: "Tangy Tomato Wafer Bites",
    slug: "tangy-tomato-wafer-bites",
    price: 129,
    originalPrice: 149,
    rating: 4.2,
    reviewCount: 22,
    image: "/images/products/tangy-tomato-wafer.png",
    category: "wafer-bites",
    badge: "-13%",
    description: "Light and crispy wafer bites with a tangy tomato twist.",
    weight: "150g",
  },
  {
    id: "8",
    name: "Spicy Peri Peri Namkeen Mix",
    slug: "spicy-peri-peri-namkeen",
    price: 179,
    originalPrice: 209,
    rating: 4.5,
    reviewCount: 53,
    image: "/images/products/peri-peri-namkeen.png",
    category: "namkeen",
    badge: "-14%",
    description:
      "Bold peri peri spiced namkeen mix — addictive crunch in every bite.",
    weight: "250g",
  },
];

export const categories: Category[] = [
  {
    id: "1",
    name: "Khakhra",
    slug: "khakhra",
    image: "/images/categories/khakhra.png",
  },
  {
    id: "2",
    name: "Healthy Chips",
    slug: "healthy-chips",
    image: "/images/categories/healthy-chips.png",
  },
  {
    id: "3",
    name: "Bakarwadi",
    slug: "bakarwadi",
    image: "/images/categories/bakarwadi.png",
  },
  {
    id: "4",
    name: "Namkeen",
    slug: "namkeen",
    image: "/images/categories/namkeen.png",
  },
  {
    id: "5",
    name: "Wafer Bites",
    slug: "wafer-bites",
    image: "/images/categories/wafer-bites.png",
  },
  {
    id: "6",
    name: "Mini Khakhras",
    slug: "mini-khakhras",
    image: "/images/categories/mini-khakhras.png",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Priya Sharma",
    text: "Absolutely love the Mini Khakhra! My kids can't stop munching on them. Healthy and tasty — what more could a mom ask for?",
    rating: 5,
    location: "Delhi",
  },
  {
    id: "2",
    name: "Rahul Verma",
    text: "The Bakarwadi Mix is just like homemade. Perfect with evening chai. Will definitely order again!",
    rating: 5,
    location: "Mumbai",
  },
  {
    id: "3",
    name: "Anita Patel",
    text: "Great quality snacks at reasonable prices. The Millet Chips are my new favourite guilt-free snack.",
    rating: 4,
    location: "Ahmedabad",
  },
  {
    id: "4",
    name: "Vikram Singh",
    text: "Fast delivery and excellent packaging. The Cheese Garlic Khakhra is to die for!",
    rating: 5,
    location: "Jaipur",
  },
];

export const tasteCategories: TasteCategory[] = [
  {
    id: "1",
    name: "Spicy & Tangy",
    slug: "spicy-tangy",
    image: "/images/taste/spicy-tangy.png",
    color: "#e65100",
  },
  {
    id: "2",
    name: "Mild & Cheesy",
    slug: "mild-cheesy",
    image: "/images/taste/mild-cheesy.jpg",
    color: "#f5a623",
  },
  {
    id: "3",
    name: "Bold & Flavorful",
    slug: "bold-flavorful",
    image: "/images/taste/bold-flavorful.jpg",
    color: "#bd0074",
  },
];

export const occasionCategories: OccasionCategory[] = [
  {
    id: "1",
    name: "Tea Time Snacks",
    slug: "tea-time",
    image: "/images/occasions/tea-time.jpg",
    description: "Perfect companions for your evening chai",
  },
  {
    id: "2",
    name: "Family Packs",
    slug: "family-packs",
    image: "/images/occasions/family-packs.jpg",
    description: "Sharing-size packs for the whole family",
  },
  {
    id: "3",
    name: "Midnight Munch",
    slug: "midnight-munch",
    image: "/images/occasions/midnight-munch.jpg",
    description: "Guilt-free late-night cravings",
  },
  {
    id: "4",
    name: "Travel Friendly",
    slug: "travel-friendly",
    image: "/images/occasions/travel-friendly.jpg",
    description: "Compact packs for on-the-go snacking",
  },
];

export const trustStats: TrustStat[] = [
  { label: "Happy Consumers", value: "10", suffix: "K+" },
  { label: "Products Sold", value: "25", suffix: "K+" },
  { label: "Customer Ratings", value: "4.5", suffix: "+" },
  { label: "Cities Across India", value: "50", suffix: "+" },
];
